# Generated by Django 4.1 on 2022-08-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMDOS', models.CharField(max_length=100)),
                ('NUMDOSVERLING', models.CharField(max_length=100)),
                ('ANCART', models.CharField(max_length=100)),
                ('FILIERE', models.CharField(max_length=100)),
                ('ETAPE', models.FloatField(max_length=100)),
                ('VERLING', models.CharField(max_length=100)),
                ('FORMAT', models.CharField(max_length=100)),
            ],
        ),
    ]
